version: '3'

volumes:
    keycloak_sample_postgres:
        driver: local
    keycloak_sample_pgadmin:

services:
    postgres:
        container_name: keycloak_sample_postgres
        image: postgres:13-alpine
        volumes:
            - keycloak_sample_postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak_sample
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - 5000:5432    
    pgadmin:
        container_name: keycloak_sample_pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - keycloak_sample_pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5051}:80"
        depends_on:
            - postgres

